import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  // Blog 侧边栏配置
  Blog: [
    {
      label: '概述',
      type: 'doc',
      id: 'Blog/introduction', // 指向 introduction.md
    },
    {
      label: 'Blog部署指南',
      type: 'category',
      link: {
        type: 'doc',
        id: 'Blog/tutorial/index',  // 指向索引页文档的 ID
      },
      collapsed: true,  // 默认折叠侧边栏
      items: [

        {
          小张的个人博客: [
            {
              type: 'doc',
              id: 'Blog/tutorial/BT/Detailed',
              label: '宝塔详细版'
            }
          ],
        },
        {
          全网最美博客: [
            {
              type: 'doc',
              id: 'Blog/tutorial/Ruyu-Blog/Ruyu-Blog',
              label: 'Ruyu-Blog V1.3.2'
            },
            {
              type: 'doc',
              id: 'Blog/tutorial/Ruyu-Blog/hitokoto',
              label: 'hitokoto'
            },
            {
              type: 'doc',
              id: 'Blog/tutorial/Ruyu-Blog/Music-module',
              label: 'Music module'
            },
            {
              type: 'doc',
              id: 'Blog/tutorial/Ruyu-Blog/Gitee',
              label: 'Gitee'
            }
          ],
        }
      ],
    },
  ], 
  skill: [
    'skill/introduction',
    {
      label: 'Docusaurus',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/Docusaurus',
        },
      ],
    },
  ], 
}

module.exports = sidebars
